// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQqBpmg0A9aC8I-z9aJHPuVEk6jDyQ9w',
    appId: '1:57937693721:web:57e19252f5b828a61dee88',
    messagingSenderId: '57937693721',
    projectId: 'dynamic-wrapper-app',
    authDomain: 'dynamic-wrapper-app.firebaseapp.com',
    storageBucket: 'dynamic-wrapper-app.firebasestorage.app',
    measurementId: 'G-1XY2QGJS1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6ZwXMRdMhCCOtz6DztOsG0RJcHDM5Xs',
    appId: '1:57937693721:android:d7cde332c7b7e5921dee88',
    messagingSenderId: '57937693721',
    projectId: 'dynamic-wrapper-app',
    storageBucket: 'dynamic-wrapper-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs4vRsyx3byfXflxLeKHSUQPgUtZ-fEKE',
    appId: '1:57937693721:ios:f356101c8c5f58231dee88',
    messagingSenderId: '57937693721',
    projectId: 'dynamic-wrapper-app',
    storageBucket: 'dynamic-wrapper-app.firebasestorage.app',
    iosBundleId: 'com.example.dynamicWrapperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs4vRsyx3byfXflxLeKHSUQPgUtZ-fEKE',
    appId: '1:57937693721:ios:f356101c8c5f58231dee88',
    messagingSenderId: '57937693721',
    projectId: 'dynamic-wrapper-app',
    storageBucket: 'dynamic-wrapper-app.firebasestorage.app',
    iosBundleId: 'com.example.dynamicWrapperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtQqBpmg0A9aC8I-z9aJHPuVEk6jDyQ9w',
    appId: '1:57937693721:web:df1e9922a01ece371dee88',
    messagingSenderId: '57937693721',
    projectId: 'dynamic-wrapper-app',
    authDomain: 'dynamic-wrapper-app.firebaseapp.com',
    storageBucket: 'dynamic-wrapper-app.firebasestorage.app',
    measurementId: 'G-QCCN3TMTWM',
  );
}
